# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Engage
email: engage@mitre.org
description: >- # this means to ignore newlines until "baseurl:"
  Engage Adversary Engagement KB
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://engage.mitre.org" # the base hostname & protocol for your site, e.g. http://example.com

search_index: "/index.json"

# If set, banner will show a colored message box under the navbar.
# To set colors, set banner_type to:
# alert-danger: red
# alert-warning: orange
# alert-success: green
# alert-info: gray
# alert-primary: primary site color
# alert-secondary: light gray
# alert-light: white
# banner: "Banner text"
# banner_type: "banner-color"

banner: "We welcome your feedback about MITRE Engage v0.9 Beta: Email us at <a href=mailto:engage@mitre.org>engage@mitre.org</a>"
banner_type: "alert-success"

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
sass:
  sass_dir: assets/css/
collections_dir: _collections
collections:
  ad_goals:
    output: true
    permalink: /goals/:path/
  ad_approaches:
    output: true
    permalink: /approaches/:path/
  ad_activities:
    output: true
    permalink: /activities/:path/
  attack_mapping:
    output: true
    permalink: /attack_mapping/:path/
  attack_groups:
    output: true
    permalink: /attack_groups/:path/
defaults:
  - scope:
      path: ""
      type: "ad_goals"
    values:
      layout: "goals"
  - scope:
      path: ""
      type: "ad_approaches"
    values:
      layout: "approaches"
  - scope:
      path: ""
      type: "ad_activities"
    values:
      layout: "activities"
  - scope:
      path: ""
      type: "attack_mapping"
    values:
      layout: "attack_tactics"
  - scope:
      path: ""
      type: "attack_groups"
    values:
      layout: "attack_groups"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
# customer excludes
  - contribute.md
  - README.md

# Google Analytics
google_analytics: G-Q9RHP807N6
